### ISSUE TITLE
Please rename this package it infringes mine

### ISSUE THREAD

**Issue by marcusts** [z33bs/SmartDi#1]
Hi, I have had this up for many years:

https://github.com/marcusts/SmartDIContainer

I am sure this was an innocent oversight.  But please do a bit more research before naming public software.  Even here on GitHub, you can find my package by searching for SmartDI.

Do confirm that this has been completed within even (7) days so I can rest assured that you have participated in GitHub according to its rules.  

marcus@marcusts.com

**Comment by z33bs** [comment]
My sincerest apologies! Rename has been completed.
